name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5.x', '2.6.x']

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: duckdb cache
      id: duckdb-cache
      uses: actions/cache@v1.1.0
      with:
        path: duckdb-v0_1_2
        key: ${{ runner.os }}-duckdb-v0_1_2_005

    - name: Build duckdb
      if: steps.duckdb-cache.outputs.cache-hit != 'true'
      run: if [[ ! -d duckdb-v0_1_2 ]]; then git clone -b v0.1.2 https://github.com/cwida/duckdb.git duckdb-v0_1_2 && cd duckdb-v0_1_2 && make && find . -type f  | grep -v so | grep -v h | xargs rm -f && rm -rf build/test build/third_party build/tools build/benchmark && find . -type f -name "*.cpp" | xargs rm -f && cd ..; fi

    - name: Build and test with Rake with Ruby ${{ matrix.ruby }}
      run: |
        find . -name "libduckdb*.so"
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake -- --with-duckdb-include=${GITHUB_WORKSPACE}/duckdb-v0_1_2/src/include --with-duckdb-lib=${GITHUB_WORKSPACE}/duckdb-v0_1_2/build/release/src/
